PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?entity ?name ?external WHERE {
  ?entity rdfs:label ?name ; owl:sameAs ?external .
  FILTER(STRSTARTS(STR(?external), "http://dbpedia.org/resource/") ||
         STRSTARTS(STR(?external), "http://www.wikidata.org/entity/"))
} ORDER BY ?entity ?external
