const root=document.body.dataset.root||'./';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>new Intl.NumberFormat('vi-VN').format(n||0);
fetch(root+'data/catalog.json').then(r=>r.json()).then(data=>{
 const section=document.body.dataset.section;
 if(section==='home') renderStats(data.stats);
 if(section==='models') renderModels(data.models);
 if(section==='organizations') renderOrganizations(data.organizations);
}).catch(e=>document.querySelectorAll('.loading').forEach(x=>x.textContent='Không đọc được catalog: '+e.message));
function renderStats(s){document.querySelector('#stats').innerHTML=[['Models',s.models],['API offerings',s.offerings],['Bản giá',s.prices],['Evaluations',s.evaluations],['Tổ chức',s.organizations],['Liên kết ngoài',s.external_links],['RDF triples',s.triples]].map(([k,v])=>`<article><strong>${fmt(v)}</strong><span>${k}</span></article>`).join('')}
function renderModels(models){const list=document.querySelector('#model-list'),detail=document.querySelector('#model-detail'),search=document.querySelector('#model-search'),filter=document.querySelector('#developer-filter'),count=document.querySelector('#model-count');[...new Set(models.map(m=>m.developer).filter(Boolean))].sort().forEach(x=>filter.insertAdjacentHTML('beforeend',`<option>${esc(x)}</option>`));function show(){const q=search.value.toLowerCase(),dev=filter.value;const found=models.filter(m=>(m.name+' '+m.source_id+' '+m.family+' '+m.developer).toLowerCase().includes(q)&&(!dev||m.developer===dev));count.textContent=`Hiển thị ${found.length} / ${models.length} model`;list.innerHTML=found.slice(0,150).map(m=>`<article class="card" data-id="${esc(m.source_id)}"><h3>${esc(m.name)}</h3><p>${esc(m.developer)} · ${esc(m.family)} · ${m.offerings.length} offerings</p></article>`).join('')||'<p>Không có kết quả.</p>';list.querySelectorAll('.card').forEach(x=>x.onclick=()=>select(models.find(m=>m.source_id===x.dataset.id)));}function select(m){history.replaceState(null,'','?id='+encodeURIComponent(m.source_id));const offer=m.offerings.slice(0,100).map(o=>`<div class="offering"><b>${esc(o.provider)}</b> <span class="tag">${esc(o.kind)}</span><p>Context: ${fmt(o.context_length)} · Max output: ${fmt(o.max_output_tokens)}</p>${o.prices.length?`<table><tr><th>Loại</th><th>Giá</th><th>Đơn vị</th></tr>${o.prices.map(p=>`<tr><td>${esc(p.category)}</td><td>${esc(p.amount)} ${esc(p.currency)}</td><td>${esc(p.unit)}</td></tr>`).join('')}</table>`:''}${o.source_url?`<a href="${esc(o.source_url)}" target="_blank" rel="noopener">Nguồn</a>`:''}</div>`).join('');detail.innerHTML=`<h2>${esc(m.name)}</h2><p><b>Developer:</b> ${esc(m.developer)}<br><b>Family:</b> ${esc(m.family)}<br><b>Source ID:</b> ${esc(m.source_id)}</p><p>${esc(m.description)}</p><p>${m.input_modalities.map(x=>`<span class="tag">input: ${esc(x)}</span>`).join('')} ${m.output_modalities.map(x=>`<span class="tag">output: ${esc(x)}</span>`).join('')}</p><details><summary>${m.capabilities.length} capabilities</summary><p>${m.capabilities.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</p></details><h3>${m.offerings.length} API offerings</h3>${offer||'<p>Chưa có offering.</p>'}<h3>${m.evaluations.length} evaluations</h3>${m.evaluations.map(e=>`<p>${esc(e.benchmark)}: <b>${esc(e.score)} ${esc(e.unit)}</b></p>`).join('')||'<p>Chưa có evaluation.</p>'}`;}search.oninput=show;filter.onchange=show;show();const id=new URLSearchParams(location.search).get('id');if(id){const m=models.find(x=>x.source_id===id);if(m)select(m)}}
function renderOrganizations(orgs){const box=document.querySelector('#org-list'),input=document.querySelector('#org-search');function show(){const q=input.value.toLowerCase();box.innerHTML=orgs.filter(o=>o.name.toLowerCase().includes(q)).map(o=>`<article class="card"><h3>${esc(o.name)}</h3><p>${o.models} models · ${o.offerings} offerings · ${o.external_links.length} external links</p>${o.external_links.map(l=>`<p><a href="${esc(l.target)}" target="_blank" rel="noopener">${esc(l.target)}</a><br><small>${esc(l.reason)}</small></p>`).join('')}</article>`).join('')}input.oninput=show;show()}
